import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Experience from './Experience/Experience'
import Navbar from './Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='-z-10 w-screen h-screen top-0 left-0 absolute blur-sm'>
          <Experience />
        </div>
        <div className=' z-50 w-screen h-screen flex flex-col'>
          <div className=''>
            <Navbar />
          </div>
          <div className='flex-1 w-full h-full px-4 pb-4'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
